## The behavior of RuboCop can be controlled via the .rubocop.yml
## configuration file. It makes it possible to enable/disable
## certain cops (checks) and to alter their behavior if they accept
## any parameters. The file can be placed either in your home
## directory or in some project directory.
##
## RuboCop will start looking for the configuration file in the directory
## where the inspected file is and continue its way up to the root directory.
##
## See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

require:
  - rubocop-rspec

AllCops:
  StyleGuideBaseURL: https://rubystyle.guide
  TargetRubyVersion: 2.7.2
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "db/migrate/*"
    - "db/fixtures/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "lib/middlewares/**"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "spec/fixtures/**/*"
    - "Gemfile"
    - "Rakefile"
    - "docker/**/*"
    - "tmp/**/*"
    - "lib/batch_scripts/*"
    - "media/config/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false

Metrics/AbcSize:
  Max: 20

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
